### ISSUE TITLE
[idea] filepath.Walk() for folders

### ISSUE THREAD

**Issue by koddr** [posener/gitfs#27]
Hi!

Would be great to add something like `filepath.Walk()` ([docs](https://golang.org/pkg/path/filepath/#Walk)) for folders from GitHub `fs`.

Or, improve `fsutil` for other files (not `*.tmpl`).

**Comment by posener** [comment]
Hey,

The [`fsutil.Walk`](https://godoc.org/github.com/posener/gitfs/fsutil#Walk) function accept any object that implements the `http.FileSystem` interface, and enables you walking over the files in that filesystem.

Does this help?

**Comment by koddr** [comment]
@posener oh, nice! Thx 👍 

I try on this way, but don't know _how to right way_:

```go
	// ...
	ctx := context.Background()
	fs, err := gitfs.New(ctx, "github.com/my-repo/configs")
	ErrChecker(err)

	walker := fsutil.Walk(fs, folderName)
	folder := appPath + string(os.PathSeparator)

	for walker.Step() {
		if err := walker.Err(); err != nil {
			fmt.Fprintln(os.Stderr, err)
			continue
		}

		folder = appPath + string(os.PathSeparator) + walker.Path()

		if !walker.Stat().IsDir() {
			fmt.Println(folder)
		}
	}
	// ...
```

p.s. some _official_ example on README — would be great 😉

**Comment by posener** [comment]
Yup, this is the right way.
You could use [`filepath.Join `](https://golang.org/pkg/path/filepath/#Join) function instead of `appPath + string(os.PathSeparator) + walker.Path()` (Which also works if one of the parts ends or starts with a separator).

> p.s. some official example on README — would be great wink

Feel free to contribute an example! Notice that the README is auto generated, so you should add an example-test in order to get it into the readme as an example.

**Comment by koddr** [comment]
Oh, sorry, forget to ask: if necessary to `defer f.Close()` when `f, err := fs.Open("file.txt")`?

**Comment by posener** [comment]
> Oh, sorry, forget to ask: if necessary to defer f.Close() when f, err := fs.Open("file.txt")?

Yes, it is common practice in Go. If err != nil in most cases you should defer the `Close()` call.
